version: '3.8'

services:
  web:
    build: .
    container_name: apache_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - lamp_network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - lamp_network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - lamp_network

  php-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: php_dev_server
    volumes:
      - ./src:/app
    ports:
      - "2024:2024"
    networks:
      - lamp_network

  nodejs:
    image: node:latest
    container_name: nodejs_app
    volumes:
      - ./node-app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm install ajax && npm install axios && npm install express && npm install nodemon --global && nodemon index.js"
    ports:
      - "3001:3000"
    networks:
      - lamp_network
volumes:
  db_data:

networks:
  lamp_network:
